apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ss
spec:
  serviceName: mysql-ss-headless
  replicas: 3
  selector:
    matchLabels:
      app: mysql-ss
  template:
    metadata:
      labels:
        app: mysql-ss
    spec:
      containers:
      - name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql     
        image: mysql:8.1.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: password
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

